[Wedibooks] 모델링 구현
wecode-bootcamp-korea/26-1st-Wedibooks-backend pull request #1
Opened 2021-11-02 10:13 UTC by hanasmile

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users, products app models.py 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 모델링한 테이블 데이터를 기준으로 models.py 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- class 값 일부 수정 후 재 makemigrations 시 오류 해결이 어려웠습니다..ㅜㅜ

<br />

## :: 기타 질문 및 특이 사항
-

2021-11-02 14:51 UTC, jamessoun93 requested changes
모델 작성하시느라 수고하셨습니다! 💯
리뷰 남겨드렸으니 확인하시고 수정해주세요 :)

2021-11-02 14:51 UTC, jamessoun93 commented on products/models.py
> +    float = models.DecimalField(max_digits=7, decimal_places=2)
필드명이 `float` 네요?! `price` 를 의미하셨을텐데 수정해주세요ㅎㅎ

2021-11-02 14:51 UTC, jamessoun93 commented on products/models.py
> +    thumbnail_img_url = models.CharField(max_length=2000)
컬럼명은 되도록이면 줄임말없이 사용해주세요!
```suggestion
    thumbnail_image_url = models.CharField(max_length=2000)
```

2021-11-02 14:51 UTC, jamessoun93 commented on products/models.py
> +    count = models.IntegerField()
`count` 보다는 `quantity` 가 더 자연스러운 컬럼명이겠네요.

2021-11-02 14:51 UTC, jamessoun93 commented on products/models.py
> +    total_price = models.DecimalField(max_digits=10, decimal_places=2)
- `total_price` 는 카트에는 불필요합니다. 
- 그때그때 담긴 `product` 들의 `price` 를 합산하면 되니까요!
- `order` 와 달리 내가 지불한 금액보다는 현재 담겨있는 상품들의 현재 가격을 합친 금액이라서요.

2021-11-02 14:51 UTC, jamessoun93 commented on products/models.py
> +    order_status = models.CharField(max_length=100)
`order_status` 는 정규화가 필요합니다.

2021-11-03 05:28 UTC, hanasmile commented on products/models.py
> +    float = models.DecimalField(max_digits=7, decimal_places=2)
수정 완료하였습니다 😊

2021-11-03 05:28 UTC, hanasmile commented on products/models.py
> +    thumbnail_img_url = models.CharField(max_length=2000)
수정 완료하였습니다 😊

2021-11-03 05:28 UTC, hanasmile commented on products/models.py
> +    count = models.IntegerField()
수정 완료하였습니다 😊

2021-11-03 05:28 UTC, hanasmile commented on products/models.py
> +    total_price = models.DecimalField(max_digits=10, decimal_places=2)
수정 완료하였습니다 😊

2021-11-03 05:28 UTC, hanasmile commented on products/models.py
> +    order_status = models.CharField(max_length=100)
수정 완료하였습니다 😊

2021-11-03 05:46 UTC, jamessoun93 approved these changes
LGTM 🚀
수고하셨습니다!

2021-11-03 05:47 UTC, merged